### ISSUE TITLE
Website icon

### ISSUE THREAD

**Issue by qgeissmann** [darsa-group/ACCESS-2024#2]
missing so far

**Comment by qgeissmann** [comment]
Something like that @melbaghooee ![icon](https://github.com/darsa-group/ACCESS-2024/assets/1399684/7273cab9-ed1d-4708-a995-8056414e1246)?

**Comment by melbaghooee** [comment]
@qgeissmann I love the logo you designed - simple and eye-catching.

I had an idea for a caterpillar holding a key with 'ACCESS' on its body. I created it roughly to visualize my idea, but I can also draw it from scratch if you like the idea. 

![Caterpillar](https://github.com/darsa-group/ACCESS-2024/assets/123562028/335df1a5-03dd-4817-a2a9-243301d0c3dc)

**Comment by qgeissmann** [comment]
Thanks @melbaghooee . Nice too! Ideally, this type of logo is squarish as it is used as a web icon by the browser: 
![image](https://github.com/darsa-group/ACCESS-2024/assets/1399684/d2eb4a8a-5e40-4029-9bbe-746e516a0a75)
Curious to hear what others think... putting it on the backburner as low priority for now

**Comment by melbaghooee** [comment]
Makes complete sense now! I think I mistook the logo for an "avatar"... In this context, the round icon is much better.
